[general]
alias = "System A"
type = 1
[server]
cert_path = "../../ssl/server.crt"
key_path = "../../ssl/server.key"
port = 4500
threads_max = 2
[standby]
cert_path = "../../ssl/standby.crt"
key_path = "../../ssl/standby.key"
address = "127.0.0.1"
port = 4501
threads_max = 2
